version: 2
updates:
  # Enable version updates for pip
  - package-ecosystem: "pip"
    # Look for `requirements.txt` in the `root` directory
    directory: "/"
    # Check once a week
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    