version: '3'

services:
  api: &api-def
    build:
      dockerfile: ./docker/Dockerfile.local
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://whatdot:postgres@db/whatdot
      - DJANGO_SETTINGS_MODULE=whatdot.settings.local

  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DB=whatdot
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=whatdot
      - POSTGRES_PASSWORD=postgres
    volumes:
      - .:/app
    ports:
      - "5432:5432"
