# Pull base image
FROM python:3.11-bullseye

# Set environment variables
ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /app

RUN apt update && \
    apt install -y postgresql-client

# Install dependencies
COPY requirements/ requirements/
RUN pip install -r requirements/local.txt

# Copy project
COPY . .

CMD python manage.py runserver 0.0.0.0:8000
