name: Django flow

on:
  pull_request:
    branches:
      - main

env:
  DATABASE_URL: postgres://whatdot:whatdot@localhost:5432/whatdot

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]
    
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: whatdot
          POSTGRES_PASSWORD: whatdot
          POSTGRES_DB: whatdot

    env:
      DB_NAME: test_db
      DB_USER: root
      DB_PASSWORD: root
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -r requirements/local.txt  
    - name: Migrate DB
      run: |
        python manage.py migrate --settings=whatdot.settings.local
    - name: Run code quality checks
      run: |
        pre-commit run --all
    # - name: Run Tests
    #   run: |
    #     pytest -m django --cov=. --cov-config=setup.cfg
      env:
          DEBUG: True
          SYSTEM_ENV: GITHUB_WORKFLOW
